baseURL = 'https://cognitive-load.dev/'
languageCode = 'en-us'
title = 'Cognitive Load'
theme = 'PaperMod'

[params]
description = "Optimize for engineering at the speed of thought."
author = "Pradeep Gollakota"
showReadingTime = true
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
comments = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/progger-dev/code-quality-blog"

[markup]
[markup.highlight]
style = "monokai"
lineNos = false
codeFences = true
guessSyntax = true

[permalinks]
posts = "/posts/:filename/"

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
